version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbbalance
      SPRING_DATASOURCE_USERNAME: balance
      SPRING_DATASOURCE_PASSWORD: 123456789
  db:
    image: sameersbn/mysql:5.7.26-0
    environment:
      DB_USER: balance
      DB_PASS: 123456789
      DB_NAME: dbbalance
    ports:
      - "3306:3306"
